DEFAULT_PG_URL=postgres://postgres:password@localhost:5431/postgres?sslmode=disable

.PHONY: .migration-up
migration-up:
	$(eval PG_URL?=$(DEFAULT_PG_URL))
	goose -dir ./migrations postgres "$(PG_URL)" up

.PHONY: .migration-down
migration-down:
	$(eval PG_URL?=$(DEFAULT_PG_URL))
	goose -dir ./migrations postgres "$(PG_URL)" down

.PHONY: .migration-status
migration-status:
	$(eval PG_URL?=$(DEFAULT_PG_URL))
	goose -dir ./migrations postgres "$(PG_URL)" status


.PHONY: .migration-create-sql
migration-create-sql:
	goose -dir ./migrations create $(filter-out $@,$(MAKECMDGOALS)) sql

.PHONY: .generate-ifacemaker
generate-ifacemaker:
	ifacemaker -f ./internal/usecase/auth.go -s Auth -i authService -p mock_usecase -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/usecase/mocks/auth.go
	ifacemaker -f ./internal/usecase/flat.go -s Flat -i flatService -p mock_usecase -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/usecase/mocks/flat.go
	ifacemaker -f ./internal/usecase/house.go -s House -i houseService -p mock_usecase -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/usecase/mocks/house.go
	ifacemaker -f ./pkg/sender/sender.go -s Sender -i senderService -p mock_usecase -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/usecase/mocks/sender.go

	ifacemaker -f ./internal/repo/user.go -s User -i userRepo -p mock_repo -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/repo/mocks/user.go
	ifacemaker -f ./internal/repo/flat.go -s Flat -i flatRepo -p mock_repo -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/repo/mocks/flat.go
	ifacemaker -f ./internal/repo/house.go -s House -i houseRepo -p mock_repo -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/repo/mocks/house.go
	ifacemaker -f ./internal/repo/subscription.go -s Subscription -i subscriptionRepo -p mock_repo -c "Code generated by ifacemaker. DO NOT EDIT." -o ./internal/repo/mocks/subscription.go

.PHONY: .generate-mocks
generate-mocks: generate-ifacemaker
	mockgen -source ./internal/repo/mocks/flat.go -destination=./internal/repo/mocks/flat_mock.go -package=mock_repo
	mockgen -source ./internal/repo/mocks/user.go -destination=./internal/repo/mocks/user_mock.go -package=mock_repo
	mockgen -source ./internal/repo/mocks/house.go -destination=./internal/repo/mocks/house_mock.go -package=mock_repo
	mockgen -source ./internal/repo/mocks/subscription.go -destination=./internal/repo/mocks/subscription_mock.go -package=mock_repo

	mockgen -source ./internal/usecase/mocks/flat.go -destination=./internal/usecase/mocks/flat_mock.go -package=mock_usecase
	mockgen -source ./internal/usecase/mocks/auth.go -destination=./internal/usecase/mocks/auth_mock.go -package=mock_usecase
	mockgen -source ./internal/usecase/mocks/house.go -destination=./internal/usecase/mocks/house_mock.go -package=mock_usecase
	mockgen -source ./internal/usecase/mocks/sender.go -destination=./internal/usecase/mocks/sender_mock.go -package=mock_usecase


	mockgen -source ./internal/repo/transactor/transactor.go -destination=./internal/repo/transactor/mocks/transactor_mock.go -package=mock_transactor