// Code generated by ifacemaker. DO NOT EDIT.

package mock_repo

import (
	"backend-bootcamp-assignment-2024/internal/domain"
	"context"
)

// flatRepo ...
type flatRepo interface {
	Create(ctx context.Context, flat domain.Flat) (uint, error)
	GetByID(ctx context.Context, id uint) (domain.Flat, error)
	UpdateStatus(ctx context.Context, id uint, status domain.FlatStatus) error
}
