// Code generated by ifacemaker. DO NOT EDIT.

package mock_repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/khostya/backend-bootcamp-assignment-2024/internal/domain"
)

// userRepo ...
type userRepo interface {
	GetByID(ctx context.Context, id uuid.UUID) (domain.User, error)
	Create(ctx context.Context, user domain.User) error
}
