// Code generated by ifacemaker. DO NOT EDIT.

package mock_usecase

import (
	"context"

	"github.com/google/uuid"
	"github.com/khostya/backend-bootcamp-assignment-2024/internal/domain"
	"github.com/khostya/backend-bootcamp-assignment-2024/internal/dto"
)

// authService ...
type authService interface {
	DummyLogin(_ context.Context, userType domain.UserType) (domain.Token, error)
	Login(ctx context.Context, param dto.LoginUserParam) (domain.Token, error)
	Register(ctx context.Context, param dto.RegisterUserParam) (uuid.UUID, error)
}
