// Code generated by ifacemaker. DO NOT EDIT.

package mock_usecase

import (
	"context"

	"github.com/khostya/backend-bootcamp-assignment-2024/internal/domain"
	"github.com/khostya/backend-bootcamp-assignment-2024/internal/dto"
)

// flatService ...
type flatService interface {
	Create(ctx context.Context, param dto.CreateFlatParam) (domain.Flat, error)
	Update(ctx context.Context, param dto.UpdateFlatParam) (domain.Flat, error)
}
