// Code generated by ifacemaker. DO NOT EDIT.

package mock_usecase

import (
	"backend-bootcamp-assignment-2024/internal/domain"
	"backend-bootcamp-assignment-2024/internal/dto"
	"context"
)

// flatService ...
type flatService interface {
	Create(ctx context.Context, param dto.CreateFlatParam) (domain.Flat, error)
	Update(ctx context.Context, param dto.UpdateFlatParam) (domain.Flat, error)
}
