// Code generated by ifacemaker. DO NOT EDIT.

package mock_usecase

import (
	"backend-bootcamp-assignment-2024/internal/domain"
	"backend-bootcamp-assignment-2024/internal/dto"
	"context"
)

// houseService ...
type houseService interface {
	GetByID(ctx context.Context, id uint) (domain.House, error)
	Create(ctx context.Context, param dto.CreateHouseParam) (domain.House, error)
	Subscribe(ctx context.Context, id int, email string) error
}
