// Code generated by ifacemaker. DO NOT EDIT.

package mock_usecase

import (
	"context"

	"github.com/khostya/backend-bootcamp-assignment-2024/internal/domain"
)

// senderService ...
type senderService interface {
	SendEmail(ctx context.Context, recipient string, message string) error
	AsyncSendEmails(ctx context.Context, subscriptions []domain.Subscription)
}
