name: ci

on:
  push:
    branches: ["*"]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Unit Test
        run: go test ./internal/... ./pkg/...

  integration-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Set Up Goose
        run: "go install github.com/pressly/goose/v3/cmd/goose@latest"

      - name: Up PG
        run: "docker compose -f docker-compose-test.yml up -d postgres-test"

      - name: Migrate
        run: "sleep 1m && goose -dir ./migrations postgres postgres://postgres:password@localhost:5430/postgres?sslmode=disable up"

      - name: Integration tests
        run: "docker compose \
          -f docker-compose-test.yml \
          up \
          --build \
          --abort-on-container-exit \
          --exit-code-from integration-postgres \
          integration-postgres"